#############################################################################
# Makefile for building: libqmltermwidget.so
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  qmltermwidget.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile qmltermwidget.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHAVE_POSIX_OPENPT -DHAVE_SYS_TIME_H -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Ilib -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmltermwidget1.0.0
DISTDIR = /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/.tmp/qmltermwidget1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -shared
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/BlockArray.cpp \
		lib/ColorScheme.cpp \
		lib/Emulation.cpp \
		lib/Filter.cpp \
		lib/History.cpp \
		lib/HistorySearch.cpp \
		lib/KeyboardTranslator.cpp \
		lib/konsole_wcwidth.cpp \
		lib/kprocess.cpp \
		lib/kpty.cpp \
		lib/kptydevice.cpp \
		lib/kptyprocess.cpp \
		lib/ProcessInfo.cpp \
		lib/Pty.cpp \
		lib/Screen.cpp \
		lib/ScreenWindow.cpp \
		lib/Session.cpp \
		lib/ShellCommand.cpp \
		lib/TerminalCharacterDecoder.cpp \
		lib/TerminalDisplay.cpp \
		lib/tools.cpp \
		lib/Vt102Emulation.cpp \
		src/qmltermwidget_plugin.cpp \
		src/ksession.cpp moc_Emulation.cpp \
		moc_Filter.cpp \
		moc_HistorySearch.cpp \
		moc_kprocess.cpp \
		moc_kptydevice.cpp \
		moc_kptyprocess.cpp \
		moc_Pty.cpp \
		moc_ScreenWindow.cpp \
		moc_Session.cpp \
		moc_TerminalDisplay.cpp \
		moc_Vt102Emulation.cpp \
		moc_qmltermwidget_plugin.cpp \
		moc_ksession.cpp
OBJECTS       = BlockArray.o \
		ColorScheme.o \
		Emulation.o \
		Filter.o \
		History.o \
		HistorySearch.o \
		KeyboardTranslator.o \
		konsole_wcwidth.o \
		kprocess.o \
		kpty.o \
		kptydevice.o \
		kptyprocess.o \
		ProcessInfo.o \
		Pty.o \
		Screen.o \
		ScreenWindow.o \
		Session.o \
		ShellCommand.o \
		TerminalCharacterDecoder.o \
		TerminalDisplay.o \
		tools.o \
		Vt102Emulation.o \
		qmltermwidget_plugin.o \
		ksession.o \
		moc_Emulation.o \
		moc_Filter.o \
		moc_HistorySearch.o \
		moc_kprocess.o \
		moc_kptydevice.o \
		moc_kptyprocess.o \
		moc_Pty.o \
		moc_ScreenWindow.o \
		moc_Session.o \
		moc_TerminalDisplay.o \
		moc_Vt102Emulation.o \
		moc_qmltermwidget_plugin.o \
		moc_ksession.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		lib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qmltermwidget.pro lib/BlockArray.h \
		lib/CharacterColor.h \
		lib/Character.h \
		lib/ColorScheme.h \
		lib/ColorTables.h \
		lib/DefaultTranslatorText.h \
		lib/Emulation.h \
		lib/ExtendedDefaultTranslator.h \
		lib/Filter.h \
		lib/History.h \
		lib/HistorySearch.h \
		lib/KeyboardTranslator.h \
		lib/konsole_wcwidth.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty.h \
		lib/kpty_p.h \
		lib/kptyprocess.h \
		lib/LineFont.h \
		lib/Pty.h \
		lib/ProcessInfo.h \
		lib/Screen.h \
		lib/ScreenWindow.h \
		lib/Session.h \
		lib/ShellCommand.h \
		lib/TerminalCharacterDecoder.h \
		lib/TerminalDisplay.h \
		lib/tools.h \
		lib/Vt102Emulation.h \
		lib/mac-vkcode.h \
		src/qmltermwidget_plugin.h \
		src/ksession.h lib/BlockArray.cpp \
		lib/ColorScheme.cpp \
		lib/Emulation.cpp \
		lib/Filter.cpp \
		lib/History.cpp \
		lib/HistorySearch.cpp \
		lib/KeyboardTranslator.cpp \
		lib/konsole_wcwidth.cpp \
		lib/kprocess.cpp \
		lib/kpty.cpp \
		lib/kptydevice.cpp \
		lib/kptyprocess.cpp \
		lib/ProcessInfo.cpp \
		lib/Pty.cpp \
		lib/Screen.cpp \
		lib/ScreenWindow.cpp \
		lib/Session.cpp \
		lib/ShellCommand.cpp \
		lib/TerminalCharacterDecoder.cpp \
		lib/TerminalDisplay.cpp \
		lib/tools.cpp \
		lib/Vt102Emulation.cpp \
		src/qmltermwidget_plugin.cpp \
		src/ksession.cpp
QMAKE_TARGET  = qmltermwidget
DESTDIR       = QMLTermWidget/
TARGET        = libqmltermwidget.so
TARGETD       = libqmltermwidget.so


first: all
####### Build rules

QMLTermWidget/libqmltermwidget.so:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d QMLTermWidget/ || mkdir -p QMLTermWidget/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) QMLTermWidget/$(TARGET)
	$(COPY_DIR) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/QMLTermWidget && $(COPY_DIR) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/QMLTermWidget && cp -f /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src/qmldir /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/QMLTermWidget && cp -f /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src/QMLTermScrollbar.qml /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/QMLTermWidget



Makefile: qmltermwidget.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		lib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qmltermwidget.pro
	$(QMAKE) -o Makefile qmltermwidget.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
lib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qmltermwidget.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qmltermwidget.pro

qmake_all: FORCE


all: Makefile QMLTermWidget/libqmltermwidget.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents lib/BlockArray.h lib/CharacterColor.h lib/Character.h lib/ColorScheme.h lib/ColorTables.h lib/DefaultTranslatorText.h lib/Emulation.h lib/ExtendedDefaultTranslator.h lib/Filter.h lib/History.h lib/HistorySearch.h lib/KeyboardTranslator.h lib/konsole_wcwidth.h lib/kprocess.h lib/kptydevice.h lib/kpty.h lib/kpty_p.h lib/kptyprocess.h lib/LineFont.h lib/Pty.h lib/ProcessInfo.h lib/Screen.h lib/ScreenWindow.h lib/Session.h lib/ShellCommand.h lib/TerminalCharacterDecoder.h lib/TerminalDisplay.h lib/tools.h lib/Vt102Emulation.h lib/mac-vkcode.h src/qmltermwidget_plugin.h src/ksession.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/BlockArray.cpp lib/ColorScheme.cpp lib/Emulation.cpp lib/Filter.cpp lib/History.cpp lib/HistorySearch.cpp lib/KeyboardTranslator.cpp lib/konsole_wcwidth.cpp lib/kprocess.cpp lib/kpty.cpp lib/kptydevice.cpp lib/kptyprocess.cpp lib/ProcessInfo.cpp lib/Pty.cpp lib/Screen.cpp lib/ScreenWindow.cpp lib/Session.cpp lib/ShellCommand.cpp lib/TerminalCharacterDecoder.cpp lib/TerminalDisplay.cpp lib/tools.cpp lib/Vt102Emulation.cpp src/qmltermwidget_plugin.cpp src/ksession.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) QMLTermWidget/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Emulation.cpp moc_Filter.cpp moc_HistorySearch.cpp moc_kprocess.cpp moc_kptydevice.cpp moc_kptyprocess.cpp moc_Pty.cpp moc_ScreenWindow.cpp moc_Session.cpp moc_TerminalDisplay.cpp moc_Vt102Emulation.cpp moc_qmltermwidget_plugin.cpp moc_ksession.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Emulation.cpp moc_Filter.cpp moc_HistorySearch.cpp moc_kprocess.cpp moc_kptydevice.cpp moc_kptyprocess.cpp moc_Pty.cpp moc_ScreenWindow.cpp moc_Session.cpp moc_TerminalDisplay.cpp moc_Vt102Emulation.cpp moc_qmltermwidget_plugin.cpp moc_ksession.cpp
moc_Emulation.cpp: lib/Emulation.h \
		lib/KeyboardTranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/Emulation.h -o moc_Emulation.cpp

moc_Filter.cpp: lib/Filter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/Filter.h -o moc_Filter.cpp

moc_HistorySearch.cpp: lib/HistorySearch.h \
		lib/Session.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/ProcessInfo.h \
		lib/ScreenWindow.h \
		lib/TerminalCharacterDecoder.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/HistorySearch.h -o moc_HistorySearch.cpp

moc_kprocess.cpp: lib/kprocess.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/kprocess.h -o moc_kprocess.cpp

moc_kptydevice.cpp: lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/kptydevice.h -o moc_kptydevice.cpp

moc_kptyprocess.cpp: lib/kptyprocess.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/kptyprocess.h -o moc_kptyprocess.cpp

moc_Pty.cpp: lib/Pty.h \
		lib/kptyprocess.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/Pty.h -o moc_Pty.cpp

moc_ScreenWindow.cpp: lib/ScreenWindow.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/KeyboardTranslator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/ScreenWindow.h -o moc_ScreenWindow.cpp

moc_Session.cpp: lib/Session.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/ProcessInfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/Session.h -o moc_Session.cpp

moc_TerminalDisplay.cpp: lib/TerminalDisplay.h \
		lib/Filter.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/qtermwidget.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		src/ksession.h \
		lib/Session.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/ProcessInfo.h \
		lib/ColorScheme.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/TerminalDisplay.h -o moc_TerminalDisplay.cpp

moc_Vt102Emulation.cpp: lib/Vt102Emulation.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/Screen.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/History.h \
		lib/BlockArray.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lib/Vt102Emulation.h -o moc_Vt102Emulation.cpp

moc_qmltermwidget_plugin.cpp: src/qmltermwidget_plugin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/qmltermwidget_plugin.h -o moc_qmltermwidget_plugin.cpp

moc_ksession.cpp: src/ksession.h \
		lib/Session.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/ProcessInfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib -I/home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ksession.h -o moc_ksession.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

BlockArray.o: lib/BlockArray.cpp lib/BlockArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlockArray.o lib/BlockArray.cpp

ColorScheme.o: lib/ColorScheme.cpp lib/ColorScheme.h \
		lib/CharacterColor.h \
		lib/tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColorScheme.o lib/ColorScheme.cpp

Emulation.o: lib/Emulation.cpp lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/Screen.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/TerminalCharacterDecoder.h \
		lib/ScreenWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Emulation.o lib/Emulation.cpp

Filter.o: lib/Filter.cpp lib/Filter.h \
		lib/TerminalCharacterDecoder.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/konsole_wcwidth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filter.o lib/Filter.cpp

History.o: lib/History.cpp lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o History.o lib/History.cpp

HistorySearch.o: lib/HistorySearch.cpp lib/TerminalCharacterDecoder.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/HistorySearch.h \
		lib/Session.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/ProcessInfo.h \
		lib/ScreenWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HistorySearch.o lib/HistorySearch.cpp

KeyboardTranslator.o: lib/KeyboardTranslator.cpp lib/KeyboardTranslator.h \
		lib/tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KeyboardTranslator.o lib/KeyboardTranslator.cpp

konsole_wcwidth.o: lib/konsole_wcwidth.cpp lib/konsole_wcwidth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o konsole_wcwidth.o lib/konsole_wcwidth.cpp

kprocess.o: lib/kprocess.cpp lib/kprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kprocess.o lib/kprocess.cpp

kpty.o: lib/kpty.cpp lib/kpty_p.h \
		lib/kpty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kpty.o lib/kpty.cpp

kptydevice.o: lib/kptydevice.cpp lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kptydevice.o lib/kptydevice.cpp

kptyprocess.o: lib/kptyprocess.cpp lib/kptyprocess.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kptyprocess.o lib/kptyprocess.cpp

ProcessInfo.o: lib/ProcessInfo.cpp lib/ProcessInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProcessInfo.o lib/ProcessInfo.cpp

Pty.o: lib/Pty.cpp lib/Pty.h \
		lib/kptyprocess.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pty.o lib/Pty.cpp

Screen.o: lib/Screen.cpp lib/Screen.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/konsole_wcwidth.h \
		lib/TerminalCharacterDecoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Screen.o lib/Screen.cpp

ScreenWindow.o: lib/ScreenWindow.cpp lib/ScreenWindow.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/KeyboardTranslator.h \
		lib/Screen.h \
		lib/History.h \
		lib/BlockArray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScreenWindow.o lib/ScreenWindow.cpp

Session.o: lib/Session.cpp lib/Session.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/ProcessInfo.h \
		lib/Pty.h \
		lib/kptyprocess.h \
		lib/kprocess.h \
		lib/kptydevice.h \
		lib/kpty_p.h \
		lib/kpty.h \
		lib/TerminalDisplay.h \
		lib/Filter.h \
		lib/qtermwidget.h \
		src/ksession.h \
		lib/ColorScheme.h \
		lib/ShellCommand.h \
		lib/Vt102Emulation.h \
		lib/Screen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Session.o lib/Session.cpp

ShellCommand.o: lib/ShellCommand.cpp lib/ShellCommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShellCommand.o lib/ShellCommand.cpp

TerminalCharacterDecoder.o: lib/TerminalCharacterDecoder.cpp lib/TerminalCharacterDecoder.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/konsole_wcwidth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerminalCharacterDecoder.o lib/TerminalCharacterDecoder.cpp

TerminalDisplay.o: lib/TerminalDisplay.cpp lib/TerminalDisplay.h \
		lib/Filter.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/qtermwidget.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		src/ksession.h \
		lib/Session.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/ProcessInfo.h \
		lib/ColorScheme.h \
		lib/konsole_wcwidth.h \
		lib/ScreenWindow.h \
		lib/TerminalCharacterDecoder.h \
		lib/LineFont.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerminalDisplay.o lib/TerminalDisplay.cpp

tools.o: lib/tools.cpp lib/tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o lib/tools.cpp

Vt102Emulation.o: lib/Vt102Emulation.cpp lib/Vt102Emulation.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/Screen.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/mac-vkcode.h \
		lib/tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vt102Emulation.o lib/Vt102Emulation.cpp

qmltermwidget_plugin.o: src/qmltermwidget_plugin.cpp src/qmltermwidget_plugin.h \
		lib/TerminalDisplay.h \
		lib/Filter.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/qtermwidget.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		src/ksession.h \
		lib/Session.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/ProcessInfo.h \
		lib/ColorScheme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmltermwidget_plugin.o src/qmltermwidget_plugin.cpp

ksession.o: src/ksession.cpp src/ksession.h \
		lib/Session.h \
		lib/Emulation.h \
		lib/KeyboardTranslator.h \
		lib/History.h \
		lib/BlockArray.h \
		lib/Character.h \
		lib/CharacterColor.h \
		lib/ProcessInfo.h \
		lib/HistorySearch.h \
		lib/ScreenWindow.h \
		lib/TerminalCharacterDecoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ksession.o src/ksession.cpp

moc_Emulation.o: moc_Emulation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Emulation.o moc_Emulation.cpp

moc_Filter.o: moc_Filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Filter.o moc_Filter.cpp

moc_HistorySearch.o: moc_HistorySearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HistorySearch.o moc_HistorySearch.cpp

moc_kprocess.o: moc_kprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kprocess.o moc_kprocess.cpp

moc_kptydevice.o: moc_kptydevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kptydevice.o moc_kptydevice.cpp

moc_kptyprocess.o: moc_kptyprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kptyprocess.o moc_kptyprocess.cpp

moc_Pty.o: moc_Pty.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Pty.o moc_Pty.cpp

moc_ScreenWindow.o: moc_ScreenWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScreenWindow.o moc_ScreenWindow.cpp

moc_Session.o: moc_Session.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Session.o moc_Session.cpp

moc_TerminalDisplay.o: moc_TerminalDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TerminalDisplay.o moc_TerminalDisplay.cpp

moc_Vt102Emulation.o: moc_Vt102Emulation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Vt102Emulation.o moc_Vt102Emulation.cpp

moc_qmltermwidget_plugin.o: moc_qmltermwidget_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmltermwidget_plugin.o moc_qmltermwidget_plugin.cpp

moc_ksession.o: moc_ksession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ksession.o moc_ksession.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget
	-$(QINSTALL_PROGRAM) QMLTermWidget/$(TARGET) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/ 


install_qmldir: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src/qmldir $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/qmldir

uninstall_qmldir: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/qmldir
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/ 


install_assets: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src/QMLTermScrollbar.qml $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes

uninstall_assets: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/ 


install_colorschemes: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/BlackOnLightYellow.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnLightYellow.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/BlackOnRandomLight.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnRandomLight.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/BlackOnWhite.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnWhite.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/BreezeModified.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BreezeModified.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/cool-retro-term.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/cool-retro-term.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/DarkPastels.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/DarkPastels.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/GreenOnBlack.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/GreenOnBlack.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/Linux.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Linux.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/Solarized.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Solarized.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/SolarizedLight.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/SolarizedLight.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/Tango.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Tango.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/Ubuntu.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Ubuntu.colorscheme
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/WhiteOnBlack.colorscheme $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/WhiteOnBlack.colorscheme

uninstall_colorschemes: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/WhiteOnBlack.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Ubuntu.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Tango.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/SolarizedLight.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Solarized.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/Linux.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/GreenOnBlack.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/DarkPastels.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/cool-retro-term.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BreezeModified.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnWhite.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnRandomLight.colorscheme
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/BlackOnLightYellow.colorscheme
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/ 


install_colorschemes2: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/BlackOnLightColor.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/BlackOnLightColor.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/DarkPicture.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/DarkPicture.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Example.Schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Example.Schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/GreenOnBlack.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenOnBlack.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/GreenTint.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenTint.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/GreenTint_MC.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenTint_MC.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/LightPicture.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/LightPicture.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Linux.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Linux.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/README.default.Schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/README.default.Schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/README.Schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/README.Schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/syscolor.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/syscolor.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Transparent.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Transparent_darkbg.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_darkbg.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Transparent_lightbg.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_lightbg.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/Transparent_MC.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_MC.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/vim.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/vim.schema
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/color-schemes/historic/XTerm.schema $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/XTerm.schema

uninstall_colorschemes2: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/XTerm.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/vim.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_MC.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_lightbg.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent_darkbg.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Transparent.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/syscolor.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/README.Schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/README.default.Schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Linux.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/LightPicture.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenTint_MC.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenTint.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/GreenOnBlack.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/Example.Schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/DarkPicture.schema
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/BlackOnLightColor.schema
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/color-schemes/historic/ 


install_kblayouts: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/default.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/default.keytab
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/historic $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/linux.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/linux.keytab
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/macbook.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/macbook.keytab
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/README $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/README
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/solaris.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/solaris.keytab
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/vt420pc.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/vt420pc.keytab

uninstall_kblayouts: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/vt420pc.keytab
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/solaris.keytab
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/README
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/macbook.keytab
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/linux.keytab
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/default.keytab
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/ 


install_kblayouts2: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/historic/vt100.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic/vt100.keytab
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/lib/kb-layouts/historic/x11r5.keytab $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic/x11r5.keytab

uninstall_kblayouts2: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic/x11r5.keytab
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic/vt100.keytab
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/kb-layouts/historic/ 


install_scrollbar: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget
	-$(QINSTALL) /home/dkroese/projects/TestApps/cool-retro-term/qmltermwidget/src/QMLTermScrollbar.qml $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml

uninstall_scrollbar: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/QMLTermScrollbar.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/qml/QMLTermWidget/ 


install: install_target install_qmldir install_assets install_colorschemes install_colorschemes2 install_kblayouts install_kblayouts2 install_scrollbar  FORCE

uninstall: uninstall_target uninstall_qmldir uninstall_assets uninstall_colorschemes uninstall_colorschemes2 uninstall_kblayouts uninstall_kblayouts2 uninstall_scrollbar  FORCE

FORCE:

